### PR TITLE
Add Form Validation with Client and Server-Side Security

### PR DESCRIPTION
**Pull request by LuisMaja**
This pull request adds form validation to ensure data is checked both on the client side and server side for security. #31

### CODE REVIEW

**Comment by cedricve** [comment]
Looks good to me but we have a build error @LuisMaja. Can you also review @KilianBoute ?

**Comment by KilianBoute** [comment]
Checked it out and the problem seems to be at the dashboard page which isn't a problem on my branch and not sure what it is exactly. 
  Collecting page data  ...TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)

**Comment by cedricve** [comment]
> Checked it out and the problem seems to be at the dashboard page which isn't a problem on my branch and not sure what it is exactly. Collecting page data ...TypeError: Object prototype may only be an Object or null: undefined at setPrototypeOf ()

Did we fix this now?

**Comment by LuisMaja** [comment]
> > Checked it out and the problem seems to be at the dashboard page which isn't a problem on my branch and not sure what it is exactly. Collecting page data ...TypeError: Object prototype may only be an Object or null: undefined at setPrototypeOf ()
> 
> Did we fix this now?

This has been fixed. The issue was that the icons folder weren't being exported from the index file in the components folder.

**Pull request merged**
